//! Property-based / fuzz round-trip tests for helium coders.
//!
//! Invariant: `decode(encode(x)) == x` for every coder, over arbitrary valid
//! inputs generated by `arbtest`.  Each test function covers one coder family
//! and respects the coder's valid-input contract (e.g. non-negative values for
//! bitpack, strictly-increasing sequences for Elias-Fano, NaN-free or
//! bitwise-comparison for Gorilla).

use arbtest::arbtest;
use helium::{
    BitpackAuto, BitpackFixed, BlockCoder, ColumnData, DataType, Delta, DeltaMin, DeltaOfDelta,
    EliasFano, GorillaXor, Leb128, Lz4, NonBlockCoder, Pcodec, Pipeline, Rle, Snappy, StageCoder,
    Zstd, compress, decompress,
};

// ---------------------------------------------------------------------------
// Small constructors that mirror roundtrip.rs style
// ---------------------------------------------------------------------------

fn nb<T: 'static + NonBlockCoder>(c: T) -> StageCoder {
    StageCoder::NonBlock(Box::new(c))
}

fn blk<T: 'static + BlockCoder>(c: T) -> StageCoder {
    StageCoder::Block(Box::new(c))
}

// ---------------------------------------------------------------------------
// Delta — I8 / I16 / I32 / I64 / U8 / U16 / U32 / U64
// ---------------------------------------------------------------------------

#[test]
fn delta_roundtrip_arbitrary_i64() {
    arbtest(|u| {
        let values: Vec<i64> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::I64, vec![nb(Delta::new(DataType::I64).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::I64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I64(values));
        Ok(())
    });
}

#[test]
fn delta_roundtrip_arbitrary_u32() {
    arbtest(|u| {
        let values: Vec<u32> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::U32, vec![nb(Delta::new(DataType::U32).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

#[test]
fn delta_roundtrip_arbitrary_i32() {
    arbtest(|u| {
        let values: Vec<i32> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::I32, vec![nb(Delta::new(DataType::I32).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::I32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I32(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// DeltaOfDelta — I64 / U32
// ---------------------------------------------------------------------------

#[test]
fn delta_of_delta_roundtrip_arbitrary_i64() {
    arbtest(|u| {
        let values: Vec<i64> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::I64,
            vec![nb(DeltaOfDelta::new(DataType::I64).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::I64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I64(values));
        Ok(())
    });
}

#[test]
fn delta_of_delta_roundtrip_arbitrary_u32() {
    arbtest(|u| {
        let values: Vec<u32> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::U32,
            vec![nb(DeltaOfDelta::new(DataType::U32).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// Leb128 — I64 / U32 / I16
// ---------------------------------------------------------------------------

#[test]
fn leb128_roundtrip_arbitrary_i64() {
    arbtest(|u| {
        let values: Vec<i64> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::I64, vec![nb(Leb128::new(DataType::I64).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::I64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I64(values));
        Ok(())
    });
}

#[test]
fn leb128_roundtrip_arbitrary_u32() {
    arbtest(|u| {
        let values: Vec<u32> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::U32, vec![nb(Leb128::new(DataType::U32).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

#[test]
fn leb128_roundtrip_arbitrary_i16() {
    arbtest(|u| {
        let values: Vec<i16> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::I16, vec![nb(Leb128::new(DataType::I16).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::I16(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I16(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// Rle — I32 / U8
// ---------------------------------------------------------------------------

#[test]
fn rle_roundtrip_arbitrary_i32() {
    arbtest(|u| {
        // Generate small values to encourage runs (but not required for correctness).
        let values: Vec<i32> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::I32, vec![nb(Rle::new(DataType::I32).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::I32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I32(values));
        Ok(())
    });
}

#[test]
fn rle_roundtrip_arbitrary_u8() {
    arbtest(|u| {
        let values: Vec<u8> = u.arbitrary()?;
        let pipeline =
            Pipeline::new(DataType::U8, vec![nb(Rle::new(DataType::U8).unwrap())]).unwrap();
        let encoded = pipeline.encode(ColumnData::U8(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U8(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// DeltaMin — I64 / U32
// ---------------------------------------------------------------------------

#[test]
fn deltamin_roundtrip_arbitrary_i64() {
    arbtest(|u| {
        let values: Vec<i64> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::I64,
            vec![blk(DeltaMin::new(DataType::I64).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::I64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I64(values));
        Ok(())
    });
}

#[test]
fn deltamin_roundtrip_arbitrary_u32() {
    arbtest(|u| {
        let values: Vec<u32> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::U32,
            vec![blk(DeltaMin::new(DataType::U32).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// BitpackFixed — non-negative inputs only.
//
// Strategy: generate `Vec<u32>` values, then clamp each to fit within
// a randomly chosen bit width (1..=32).  This keeps all values in-domain.
// ---------------------------------------------------------------------------

#[test]
fn bitpack_fixed_roundtrip_arbitrary_u32() {
    arbtest(|u| {
        // Pick a bit width in [1, 32].
        let width = (u.arbitrary::<u8>()? % 32) + 1;
        let max_val: u32 = if width >= 32 {
            u32::MAX
        } else {
            (1u32 << width) - 1
        };
        // Clamp each element to [0, max_val] so they fit.
        let raw: Vec<u32> = u.arbitrary()?;
        let values: Vec<u32> = raw.into_iter().map(|v| v & max_val).collect();

        let pipeline = Pipeline::new(
            DataType::U32,
            vec![nb(BitpackFixed::new(DataType::U32, width as u32).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

#[test]
fn bitpack_fixed_roundtrip_arbitrary_u64() {
    arbtest(|u| {
        // Pick a bit width in [1, 64].
        let width = (u.arbitrary::<u8>()? % 64) + 1;
        let max_val: u64 = if width >= 64 {
            u64::MAX
        } else {
            (1u64 << width) - 1
        };
        let raw: Vec<u64> = u.arbitrary()?;
        let values: Vec<u64> = raw.into_iter().map(|v| v & max_val).collect();

        let pipeline = Pipeline::new(
            DataType::U64,
            vec![nb(BitpackFixed::new(DataType::U64, width as u32).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U64(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// BitpackAuto — non-negative inputs; values may be full-range unsigned.
// ---------------------------------------------------------------------------

#[test]
fn bitpack_auto_roundtrip_arbitrary_u32() {
    arbtest(|u| {
        let values: Vec<u32> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::U32,
            vec![blk(BitpackAuto::new(DataType::U32).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

#[test]
fn bitpack_auto_roundtrip_arbitrary_u64() {
    arbtest(|u| {
        let values: Vec<u64> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::U64,
            vec![blk(BitpackAuto::new(DataType::U64).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U64(values));
        Ok(())
    });
}

#[test]
fn bitpack_auto_roundtrip_arbitrary_non_negative_i64() {
    arbtest(|u| {
        // BitpackAuto requires non-negative values for signed types.
        // Map into [0, i64::MAX] via unsigned_abs + mask — note plain `v.abs()`
        // would panic on i64::MIN (negation overflow) in debug builds.
        let raw: Vec<i64> = u.arbitrary()?;
        let values: Vec<i64> = raw
            .into_iter()
            .map(|v| (v.unsigned_abs() & i64::MAX as u64) as i64)
            .collect();

        let pipeline = Pipeline::new(
            DataType::I64,
            vec![blk(BitpackAuto::new(DataType::I64).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::I64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I64(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// GorillaXor — F32 / F64.
//
// NaN handling: NaN != NaN under `==`, so we compare bit-for-bit via `to_bits`.
// We use arbitrary floats (including NaN) because the coder must round-trip
// any bit pattern.  The existing gorilla_f64_handles_special_values test uses
// the same bitwise comparison strategy.
// ---------------------------------------------------------------------------

#[test]
fn gorilla_f64_roundtrip_arbitrary() {
    arbtest(|u| {
        let bits: Vec<u64> = u.arbitrary()?;
        // Reconstruct f64 values from raw bits — this includes NaN / ±inf.
        let values: Vec<f64> = bits.iter().map(|&b| f64::from_bits(b)).collect();

        let pipeline = Pipeline::new(
            DataType::F64,
            vec![nb(GorillaXor::new(DataType::F64).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::F64(values.clone())).unwrap();
        let ColumnData::F64(decoded_vals) = pipeline.decode(encoded).unwrap() else {
            panic!("expected F64");
        };
        // Bitwise comparison to handle NaN correctly.
        assert_eq!(decoded_vals.len(), values.len());
        for (orig, got) in values.iter().zip(decoded_vals.iter()) {
            assert_eq!(
                orig.to_bits(),
                got.to_bits(),
                "bit mismatch: orig={orig} got={got}"
            );
        }
        Ok(())
    });
}

#[test]
fn gorilla_f32_roundtrip_arbitrary() {
    arbtest(|u| {
        let bits: Vec<u32> = u.arbitrary()?;
        let values: Vec<f32> = bits.iter().map(|&b| f32::from_bits(b)).collect();

        let pipeline = Pipeline::new(
            DataType::F32,
            vec![nb(GorillaXor::new(DataType::F32).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::F32(values.clone())).unwrap();
        let ColumnData::F32(decoded_vals) = pipeline.decode(encoded).unwrap() else {
            panic!("expected F32");
        };
        assert_eq!(decoded_vals.len(), values.len());
        for (orig, got) in values.iter().zip(decoded_vals.iter()) {
            assert_eq!(
                orig.to_bits(),
                got.to_bits(),
                "bit mismatch: orig={orig} got={got}"
            );
        }
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// EliasFano — strictly-increasing U32 / U64 sequences.
//
// Monotonicity strategy: generate an arbitrary Vec<u32>, sort it, then dedup
// to ensure strict increase.  The coder rejects equal values (non-decreasing
// is not enough — it requires strictly increasing).  An empty or single-element
// result is also valid.
// ---------------------------------------------------------------------------

#[test]
fn elias_fano_roundtrip_arbitrary_monotonic_u32() {
    arbtest(|u| {
        let mut raw: Vec<u32> = u.arbitrary()?;
        raw.sort_unstable();
        raw.dedup(); // strictly increasing after sort + dedup
        let values = raw;

        let pipeline = Pipeline::new(
            DataType::U32,
            vec![blk(EliasFano::new(DataType::U32).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

#[test]
fn elias_fano_roundtrip_arbitrary_monotonic_u64() {
    arbtest(|u| {
        let mut raw: Vec<u64> = u.arbitrary()?;
        raw.sort_unstable();
        raw.dedup();
        let values = raw;

        let pipeline = Pipeline::new(
            DataType::U64,
            vec![blk(EliasFano::new(DataType::U64).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U64(values));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// Zstd — arbitrary bytes
// ---------------------------------------------------------------------------

#[test]
fn zstd_roundtrip_arbitrary_bytes() {
    arbtest(|u| {
        let bytes: Vec<u8> = u.arbitrary()?;
        let pipeline = Pipeline::new(DataType::Bytes, vec![blk(Zstd::default())]).unwrap();
        let encoded = pipeline.encode(ColumnData::Bytes(bytes.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::Bytes(bytes));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// Lz4 — arbitrary bytes
// ---------------------------------------------------------------------------

#[test]
fn lz4_roundtrip_arbitrary_bytes() {
    arbtest(|u| {
        let bytes: Vec<u8> = u.arbitrary()?;
        let pipeline = Pipeline::new(DataType::Bytes, vec![blk(Lz4)]).unwrap();
        let encoded = pipeline.encode(ColumnData::Bytes(bytes.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::Bytes(bytes));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// Snappy — arbitrary bytes
// ---------------------------------------------------------------------------

#[test]
fn snappy_roundtrip_arbitrary_bytes() {
    arbtest(|u| {
        let bytes: Vec<u8> = u.arbitrary()?;
        let pipeline = Pipeline::new(DataType::Bytes, vec![blk(Snappy)]).unwrap();
        let encoded = pipeline.encode(ColumnData::Bytes(bytes.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::Bytes(bytes));
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// Pcodec — numeric (I32 / I64 / U32 / U64 / F32 / F64)
// ---------------------------------------------------------------------------

#[test]
fn pcodec_roundtrip_arbitrary_i64() {
    arbtest(|u| {
        let values: Vec<i64> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::I64,
            vec![blk(Pcodec::new(DataType::I64, None).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::I64(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::I64(values));
        Ok(())
    });
}

#[test]
fn pcodec_roundtrip_arbitrary_u32() {
    arbtest(|u| {
        let values: Vec<u32> = u.arbitrary()?;
        let pipeline = Pipeline::new(
            DataType::U32,
            vec![blk(Pcodec::new(DataType::U32, None).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::U32(values.clone())).unwrap();
        let decoded = pipeline.decode(encoded).unwrap();
        assert_eq!(decoded, ColumnData::U32(values));
        Ok(())
    });
}

#[test]
fn pcodec_roundtrip_arbitrary_f64() {
    // Pcodec operates on raw float bits — NaN round-trips bitwise.
    arbtest(|u| {
        let bits: Vec<u64> = u.arbitrary()?;
        let values: Vec<f64> = bits.iter().map(|&b| f64::from_bits(b)).collect();

        let pipeline = Pipeline::new(
            DataType::F64,
            vec![blk(Pcodec::new(DataType::F64, None).unwrap())],
        )
        .unwrap();
        let encoded = pipeline.encode(ColumnData::F64(values.clone())).unwrap();
        let ColumnData::F64(decoded_vals) = pipeline.decode(encoded).unwrap() else {
            panic!("expected F64");
        };
        assert_eq!(decoded_vals.len(), values.len());
        for (orig, got) in values.iter().zip(decoded_vals.iter()) {
            assert_eq!(orig.to_bits(), got.to_bits());
        }
        Ok(())
    });
}

// ---------------------------------------------------------------------------
// Higher-level: round-trip through the top-level `compress` / `decompress`
// (HEC0) API for I64 and Bytes — exercises the whole default-pipeline path.
// ---------------------------------------------------------------------------

#[test]
fn hec0_compress_decompress_arbitrary_i64() {
    arbtest(|u| {
        let values: Vec<i64> = u.arbitrary()?;
        let data = ColumnData::I64(values.clone());
        let compressed = compress(data).unwrap();
        let recovered = decompress(&compressed).unwrap();
        assert_eq!(recovered, ColumnData::I64(values));
        Ok(())
    });
}

#[test]
fn hec0_compress_decompress_arbitrary_bytes() {
    arbtest(|u| {
        let bytes: Vec<u8> = u.arbitrary()?;
        let data = ColumnData::Bytes(bytes.clone());
        let compressed = compress(data).unwrap();
        let recovered = decompress(&compressed).unwrap();
        assert_eq!(recovered, ColumnData::Bytes(bytes));
        Ok(())
    });
}

#[test]
fn hec0_compress_decompress_arbitrary_f64() {
    arbtest(|u| {
        // Use bit-based construction so NaN is included.
        let bits: Vec<u64> = u.arbitrary()?;
        let values: Vec<f64> = bits.iter().map(|&b| f64::from_bits(b)).collect();
        let data = ColumnData::F64(values.clone());
        let compressed = compress(data).unwrap();
        let ColumnData::F64(recovered) = decompress(&compressed).unwrap() else {
            panic!("expected F64");
        };
        assert_eq!(recovered.len(), values.len());
        for (orig, got) in values.iter().zip(recovered.iter()) {
            assert_eq!(orig.to_bits(), got.to_bits());
        }
        Ok(())
    });
}
