//! Candidate encoding pipeline generator.
//!
//! Each function returns a list of `LeafCandidate` items — (label, coders) pairs
//! representing heuristic-curated pipeline options for a physical leaf column.
//! The picker module selects among them by measuring compressed size on sample data.
//!
//! # Role semantics
//!
//! Physical leaf columns fall into two categories:
//! - **Structural roles**: `offsets`, `outer_offsets`, `inner_offsets`, `dict_offsets`,
//!   `present`, `tag`, `indices` — generated by the container types (List, Map,
//!   Nullable, Union, Dict*).  Pipeline choices are role-driven heuristics.
//! - **Data roles**: `values`, `data`, `dict_values`, `dict_data` — the actual
//!   user-visible column data.  Pipeline choices are data-type-driven heuristics.

use crate::{CoderSpec, ColumnData};

/// A candidate pipeline for a single physical leaf.
#[derive(Debug, Clone)]
pub struct LeafCandidate {
    /// Human-readable label for diagnostics.
    pub label: String,
    /// Ordered pipeline stages.  Must form a valid pipeline ending in `Bytes`.
    pub coders: Vec<CoderSpec>,
}

impl LeafCandidate {
    fn new(label: impl Into<String>, coders: Vec<CoderSpec>) -> Self {
        Self {
            label: label.into(),
            coders,
        }
    }
}

/// Generate heuristic candidates for a **structural** leaf based on its role name.
///
/// Structural leaves are generated by container types (List, Map, Nullable, Union,
/// Dict*) rather than user-visible column data.  The `data` argument is used for
/// cardinality / range checks.
///
/// `terminal` must be one of `"zstd"`, `"lz4"`, `"snappy"`.
pub fn structural_candidates(
    role: &str,
    data: &ColumnData,
    terminal: &CoderSpec,
) -> Vec<LeafCandidate> {
    let tc = || terminal.clone();

    match role {
        // -----------------------------------------------------------------------
        // Monotonically-increasing U32 offsets (List, Map, ArrayOf, Utf8, Binary).
        // Delta coding is ideal; deltamin+bitpack is also strong.
        // -----------------------------------------------------------------------
        "offsets" | "outer_offsets" | "inner_offsets" | "dict_offsets" => {
            let mut out = vec![
                LeafCandidate::new(
                    "offsets:delta+leb128",
                    vec![CoderSpec::new("delta"), CoderSpec::new("leb128"), tc()],
                ),
                LeafCandidate::new("offsets:pcodec", vec![CoderSpec::new("pcodec")]),
                LeafCandidate::new(
                    "offsets:deltamin+bitpack_auto",
                    vec![
                        CoderSpec::new("deltamin"),
                        CoderSpec::new("bitpack_auto"),
                        tc(),
                    ],
                ),
            ];
            // Elias-Fano for monotonic U32 (great for sparse or wide ranges)
            if matches!(data, ColumnData::U32(_)) {
                out.push(LeafCandidate::new(
                    "offsets:elias_fano",
                    vec![CoderSpec::new("elias_fano"), tc()],
                ));
            }
            out
        }

        // -----------------------------------------------------------------------
        // U8 present bitmap (Nullable).  Boolean values — RLE excels.
        // -----------------------------------------------------------------------
        "present" => {
            vec![
                LeafCandidate::new(
                    "present:rle+bitpack_auto",
                    vec![CoderSpec::new("rle"), CoderSpec::new("bitpack_auto"), tc()],
                ),
                LeafCandidate::new("present:leb128", vec![CoderSpec::new("leb128"), tc()]),
            ]
        }

        // -----------------------------------------------------------------------
        // U8 tag column (Union).  Low cardinality — RLE is usually best.
        // -----------------------------------------------------------------------
        "tag" => {
            vec![
                LeafCandidate::new(
                    "tag:rle+bitpack_auto",
                    vec![CoderSpec::new("rle"), CoderSpec::new("bitpack_auto"), tc()],
                ),
                LeafCandidate::new("tag:leb128", vec![CoderSpec::new("leb128"), tc()]),
            ]
        }

        // -----------------------------------------------------------------------
        // U32 dictionary indices.
        // -----------------------------------------------------------------------
        "indices" => {
            vec![
                LeafCandidate::new(
                    "indices:bitpack_auto",
                    vec![CoderSpec::new("bitpack_auto"), tc()],
                ),
                LeafCandidate::new("indices:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new("indices:pcodec", vec![CoderSpec::new("pcodec")]),
            ]
        }

        // -----------------------------------------------------------------------
        // Byte buffer roles (terminal-only).
        // -----------------------------------------------------------------------
        "data" | "dict_data" => bytes_candidates(terminal),

        // -----------------------------------------------------------------------
        // Dictionary value columns — treat as data candidates of their type.
        // -----------------------------------------------------------------------
        _ if role.starts_with("dict_values") => data_candidates_for(data, terminal),

        // -----------------------------------------------------------------------
        // Unknown structural role — fall through to data candidates.
        // -----------------------------------------------------------------------
        _ => data_candidates_for(data, terminal),
    }
}

/// Generate heuristic candidates for a **data** leaf based on its content.
///
/// `data` determines both which pipeline shapes are valid and — for I32/I64 —
/// whether non-negative fast-paths (`deltamin`) apply.
pub fn data_candidates(data: &ColumnData, terminal: &CoderSpec) -> Vec<LeafCandidate> {
    data_candidates_for(data, terminal)
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn data_candidates_for(data: &ColumnData, terminal: &CoderSpec) -> Vec<LeafCandidate> {
    let tc = || terminal.clone();

    match data {
        ColumnData::I32(v) => {
            let mut out = vec![
                LeafCandidate::new("i32:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new(
                    "i32:delta+leb128",
                    vec![CoderSpec::new("delta"), CoderSpec::new("leb128"), tc()],
                ),
                LeafCandidate::new(
                    "i32:dod+leb128",
                    vec![
                        CoderSpec::new("delta_of_delta"),
                        CoderSpec::new("leb128"),
                        tc(),
                    ],
                ),
                LeafCandidate::new("i32:pcodec", vec![CoderSpec::new("pcodec")]),
                LeafCandidate::new(
                    "i32:rle+leb128",
                    vec![CoderSpec::new("rle"), CoderSpec::new("leb128"), tc()],
                ),
            ];
            // deltamin+bitpack_auto only for non-negative values
            if v.iter().all(|&x| x >= 0) {
                out.push(LeafCandidate::new(
                    "i32:deltamin+bitpack_auto",
                    vec![
                        CoderSpec::new("deltamin"),
                        CoderSpec::new("bitpack_auto"),
                        tc(),
                    ],
                ));
            }
            out
        }

        ColumnData::I64(v) => {
            let mut out = vec![
                LeafCandidate::new("i64:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new(
                    "i64:delta+leb128",
                    vec![CoderSpec::new("delta"), CoderSpec::new("leb128"), tc()],
                ),
                LeafCandidate::new(
                    "i64:dod+leb128",
                    vec![
                        CoderSpec::new("delta_of_delta"),
                        CoderSpec::new("leb128"),
                        tc(),
                    ],
                ),
                LeafCandidate::new("i64:pcodec", vec![CoderSpec::new("pcodec")]),
            ];
            if v.iter().all(|&x| x >= 0) {
                out.push(LeafCandidate::new(
                    "i64:deltamin+bitpack_auto",
                    vec![
                        CoderSpec::new("deltamin"),
                        CoderSpec::new("bitpack_auto"),
                        tc(),
                    ],
                ));
            }
            out
        }

        ColumnData::I8(_) | ColumnData::I16(_) => {
            vec![
                LeafCandidate::new("int:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new(
                    "int:delta+leb128",
                    vec![CoderSpec::new("delta"), CoderSpec::new("leb128"), tc()],
                ),
                LeafCandidate::new("int:pcodec", vec![CoderSpec::new("pcodec")]),
            ]
        }

        ColumnData::U8(_) => {
            // U8 often appears as tag or present; for raw U8 data offer leb128 and pcodec.
            vec![
                LeafCandidate::new("u8:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new(
                    "u8:rle+bitpack_auto",
                    vec![CoderSpec::new("rle"), CoderSpec::new("bitpack_auto"), tc()],
                ),
                LeafCandidate::new("u8:pcodec", vec![CoderSpec::new("pcodec")]),
            ]
        }

        ColumnData::U16(_) => {
            vec![
                LeafCandidate::new("u16:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new(
                    "u16:bitpack_auto",
                    vec![CoderSpec::new("bitpack_auto"), tc()],
                ),
                LeafCandidate::new("u16:pcodec", vec![CoderSpec::new("pcodec")]),
            ]
        }

        ColumnData::U32(v) => {
            let mut out = vec![
                LeafCandidate::new("u32:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new(
                    "u32:bitpack_auto",
                    vec![CoderSpec::new("bitpack_auto"), tc()],
                ),
                LeafCandidate::new("u32:pcodec", vec![CoderSpec::new("pcodec")]),
            ];
            // Check if monotonic (all non-decreasing) → add delta candidates
            if is_monotonic_u32(v) {
                out.push(LeafCandidate::new(
                    "u32:delta+leb128",
                    vec![CoderSpec::new("delta"), CoderSpec::new("leb128"), tc()],
                ));
                out.push(LeafCandidate::new(
                    "u32:deltamin+bitpack_auto",
                    vec![
                        CoderSpec::new("deltamin"),
                        CoderSpec::new("bitpack_auto"),
                        tc(),
                    ],
                ));
            }
            out
        }

        ColumnData::U64(_) => {
            vec![
                LeafCandidate::new("u64:leb128", vec![CoderSpec::new("leb128"), tc()]),
                LeafCandidate::new("u64:pcodec", vec![CoderSpec::new("pcodec")]),
            ]
        }

        ColumnData::F32(_) => {
            vec![
                LeafCandidate::new("f32:gorilla", vec![CoderSpec::new("gorilla"), tc()]),
                LeafCandidate::new("f32:pcodec", vec![CoderSpec::new("pcodec")]),
            ]
        }

        ColumnData::F64(_) => {
            vec![
                LeafCandidate::new("f64:gorilla", vec![CoderSpec::new("gorilla"), tc()]),
                LeafCandidate::new("f64:pcodec", vec![CoderSpec::new("pcodec")]),
            ]
        }

        ColumnData::Bytes(_) => bytes_candidates(terminal),
    }
}

/// Candidates for a raw `Bytes` leaf (string data, binary data).
///
/// The terminal compressor (and its level) is a global setting on the
/// optimizer config — it is not searched per-leaf, so there is a single
/// candidate here.
fn bytes_candidates(terminal: &CoderSpec) -> Vec<LeafCandidate> {
    vec![LeafCandidate::new(
        format!("bytes:{}", terminal.id),
        vec![terminal.clone()],
    )]
}

fn is_monotonic_u32(v: &[u32]) -> bool {
    v.windows(2).all(|w| w[1] >= w[0])
}

// ---------------------------------------------------------------------------
// Cardinality helpers (used by the optimizer for dict promotion decisions)
// ---------------------------------------------------------------------------

/// Returns the number of distinct I32 values if ≤ `limit`, else `None`.
pub fn distinct_i32(values: &[i32], limit: usize) -> Option<usize> {
    let mut set = std::collections::HashSet::new();
    for &v in values {
        set.insert(v);
        if set.len() > limit {
            return None;
        }
    }
    Some(set.len())
}

/// Returns the number of distinct I64 values if ≤ `limit`, else `None`.
pub fn distinct_i64(values: &[i64], limit: usize) -> Option<usize> {
    let mut set = std::collections::HashSet::new();
    for &v in values {
        set.insert(v);
        if set.len() > limit {
            return None;
        }
    }
    Some(set.len())
}

/// Returns the number of distinct `&str` values if ≤ `limit`, else `None`.
pub fn distinct_str(values: &[String], limit: usize) -> Option<usize> {
    let mut set = std::collections::HashSet::new();
    for v in values {
        set.insert(v.as_str());
        if set.len() > limit {
            return None;
        }
    }
    Some(set.len())
}
